Added updated squash and README.md for scripts

diff --git a/scripts/squash b/scripts/squash
--- a/scripts/squash
+++ b/scripts/squash
@@ -1,248 +1,319 @@
 #!/usr/bin/env bash
+#
+# -- squash : simple bash script to apply color themes to unix systems
+# -- Author : Joshua L Ervin @ University of Washinton
+# -- Contact: jlervin@posteo.net 
 
-# Get command line arguments
-COLOR_SCHEME="$1"
-
-# Define location of cache and themes
-CACHE_DIR=$HOME/.cache/squash
-THEME_DIR=$HOME/.config/squash
-WM=$(head -n 1 $CACHE_DIR/wm)
-
-# Make newlines easier, and define sequence
+COLOR_SCHEME="${1}"
+SQUASH_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 NEWLINE=$'\n'
-sequence=""
 
-# remove old cache files
-cleanup() 
+source "${SQUASH_DIR}/defaults"
+
+function usage() 
 {
-   rm -f $CACHE_DIR/x_colors
+    printf "Usage: squash <THEME_NAME>\n"
+    printf "Example: squash designr\n"
+    printf "         squash -b -w designr\n"
+    printf "\n"
+    exit 1
 }
 
-# reloads xterminals in place
-reload_x() 
+test -z "${1}" && usage
+
+if [[ ! -f ${THEME_DIR}/${COLOR_SCHEME} ]]; then
+    printf "Error: Colorscheme not found\n"
+    printf "Exiting program\n"
+    exit 0
+fi
+
+# Source necessary squash files
+#source "${SQUASH_DIR}/defaults"
+source "${THEME_DIR}/${COLOR_SCHEME}"
+
+color_array=($BLK $RED $GRN $YLW $BLU $MAG $CYN $WHT \
+             $BBLK $BRED $BGRN $BYLW $BBLU $BMAG $BCYN $BWHT)
+
+# Uses the sourced color array to create a sequence
+# of escape codes for x terminals, and update their
+# colors without restarting them
+function update_terminals() 
 {
-   for term in /dev/pts/[0-9]*; do
-      printf "%b" "$sequence" > "$term"
-   done
+    local sequence=""
+
+    for i in {0..15}; do 
+        sequence+="\033]4;${i};${color_array[${i}]}\007"
+    done
+    for i in 10 12 13; do 
+        sequence+="\033]${i};${FG}\007"
+    done
+    for i in 11 14 708; do 
+        sequence+="\033]${i};${BG}\007"
+    done
+    
+    if [[ $SQUASH_FONT ]]; then
+        sequence+="\033]50;${SQUASH_FONT}\007"
+        sequence+="\033]711;${SQUASH_FONT}\007"
+    fi
+
+
+    reload_terminals "${sequence}"
 }
 
-merge_x() 
+# Identifies the current window manager 
+# and reloads the given window manager using the
+# given colors. 
+# Notes:
+#   Requires wmctrl to identify window manager
+function update_wm() 
 {
-   xrdb ${HOME}/.Xresources
+    if [[ ! $(command -v wmctrl) ]]; then
+        printf "Error: cmtrl not found, wm will not be reloaded\n"
+    else
+        wm=$(wmctrl -m | grep Name | cut -d' ' -f2)
+        case ${wm} in
+            $"2bwm")
+                reload_2bwm
+            ;;
+            $"bspwm")
+                reload_bspwm
+            ;;
+            $"windowchef")
+                reload_chef
+            ;;
+        esac
+    fi
 }
 
-# kills old polybar and reloads
-reload_polybar() 
+# Updates neovim by overwriting the current colorscheme in the .vimrc
+# and sending remote commands to source $MYVIMRC to all vim instances
+# Notes:
+#   Requires neovim-remote to function
+#   Will overwrite the current theme in you .vimrc 
+function update_nvim()
 {
-   pkill -x polybar
-   polybar base &
+    if [[ -z ${VIM_SCHEME} ]]; then
+        printf "Error: VIM_SCHEME not set: not changing vim colorscheme\n"
+    else
+        sed -i -e "s/colorscheme .*/colorscheme $VIM_SCHEME/g" $VIM_CONFIG
+        reload_nvim
+    fi
 }
 
-reload_lemonbar() 
+# Kills all current instances of lemonbar and starts the current bar in the background
+# Notes:
+function update_bar() 
 {
-   pkill -x lemonbar
-   teny &
+    if [[ $(pgrep lemonbar) ]]; then
+        pkill -x lemonbar
+    elif [[ $(pgrep polybar) ]]; then
+        pkill -x polybar
+    fi
+    ( ${BAR_SCRIPT} &) > /dev/null 2>&1
 }
 
-# Credit for this method goes to dkeg
-# github.com/dkeg
-reload_2bwm() 
+function update_wall()
 {
-   foc=$ylw
-   unfoc=$blu
-   fixc=$red
-   unkil=$cyn
-   fixunk=$mag
-   outr=$bg
-   emp=$bg
-
-   dir=$HOME/2bwm
-   file=$dir/config.h
-
-   printf "${NEWLINE}"
-   printf "${dir}${NEWLINE}"
-   printf "${file}${NEWLINE}"
-
-   wmcol=$(cat $file|awk '/\*colors/ {print $6}'|cut -d '}' -f1|awk '{gsub(/"/," ");print $2,$4,$6,$8,$10,$12,$14}') 
-   arr=($wmcol)
-
-    sed -i "s/${arr[0]}/"$foc"/;
-            s/${arr[1]}/"$unfoc"/;
-            s/${arr[2]}/"$fixc"/;
-            s/${arr[3]}/"$unkil"/;
-            s/${arr[4]}/"$fixunk"/;
-            s/${arr[5]}/"$outr"/;
-            s/${arr[6]}/"$emp"/" $file 
-
-   cd $dir && make && sudo make install && cd
-
-   xdotool key "super+ctrl+r"
+    if [[ -z ${WALLPAPER_PATH} ]]; then
+        printf "Error: WALLPAPER_PATH not set: not changing wallpaper\n"
+    else
+        hsetroot -"${WALLPAPER_STYLE}" "${WALLPAPER_PATH}"
+    fi
 }
 
-set_wallpaper() 
+function update_dunst()
 {
-   hsetroot -fill ${wallpaper}
-   cp ${wallpaper} "/tmp/screen.png"
+    if [[ -z ${DUNST_PATH} ]]; then
+        printf "Error: Dunst path not set: not reloading dunst\n"
+    else
+        killall dunst
+        sed -i "s/background.*/background = \"${BLK}\"/g" "${DUNST_PATH}"
+        sed -i "s/foreground.*/foreground = \"${FG}\"/g" "${DUNST_PATH}"
+        dunst &
+        notify-send "DUNST RELOADED"
+    fi
 }
 
-# builds an array of all necessary colors
-# the last three elements of the array are
-# the bg, fg, and cursor color
-get_colors() 
+# Updates 2bwm's config.h with the new system colors
+# Recompiles 2bwm and reloads the window manager
+# Kills all current instances of lemonbar and starts the current bar in the background
+# Globals:
+#   TWOBWM_FOCUS
+#   TWOBWM_UNFOCUS
+#   TWOBWM_FIXED
+#   TWOBWM_UNKILL
+#   TWOBWM_FIXEDUNK
+#   TWOBWM_OUTR
+#   TWOBWM_EMP
+#   TWOBWM_PATH
+# Notes:
+#   Requires xdotool to reload 2bwm
+function reload_2bwm() 
 {
-   . $THEME_DIR/$COLOR_SCHEME
-   COLOR_ARRAY=($blk $red $grn $ylw $blu $mag $cyn $wht \
-                $bblk $bred $bgrn $bylw $bblu $bmag $bcyn $bwht)
+    local dir="${TWOBWM_PATH}"
+    local file="${TWOBWM_PATH}/config.h"
+
+    local wmcol=$(cat ${file}|awk '/\*colors/ {print $6}'|cut -d '}' -f1|awk '{gsub(/"/," ");print $2,$4,$6,$8,$10,$12,$14}') 
+    local arr=($wmcol)
+
+    sed -i "s/${arr[0]}/"${TWOBWM_FOCUS}"/;
+            s/${arr[1]}/"${TWOBWM_UNFOCUS}"/;
+            s/${arr[2]}/"${TWOBWM_FIXED}"/;
+            s/${arr[3]}/"${TWOBWM_UNKILL}"/;
+            s/${arr[4]}/"${TWOBWM_FIXEDUNK}"/;
+            s/${arr[5]}/"${TWOBWM_OUTR}"/;
+            s/${arr[6]}/"${TWOBWM_EMP}"/" ${file} 
+
+    cd ${dir} && make && sudo make install && cd
+
+    xdotool key "super+ctrl+r"
 }
 
-# adds main colors to sequence 0-15. Colors are defined in the 
-# COLOR_ARRAY
-create_main_sequence() 
+function reload_bspwm()
 {
-   for i in {0..15}
-   do
-      sequence+="\033]4;${i};${COLOR_ARRAY[${i}]}\007"
-   done
+    if [[ -z ${BSPWM_PATH} ]]; then
+        printf "Error: BSPWM_PATH not found, not reloading bspwm\n"
+    else
+        "${BSPWM_PATH}/bspwmrc" &
+    fi
 }
 
-# adds background and foreground colors to sequence
-# does not rely on array, uses sourced variables
-create_secondary_sequence() 
+function reload_chef()
 {
-   # add foreground
-   for i in 10 12 13; do
-      sequence+="\033]${i};${fg}\007"
-   done
-
-   # add background
-   for i in 11 14 708; do
-      sequence+="\033]${i};${bg}\007"
-   done
+    if [[ -z ${CHEF_PATH} ]]; then
+        printf "Error: CHEF_PATH not found, not reloading windowchef\n"
+    else
+        "${CHEF_PATH}/windowchefrc" &
+    fi
 }
 
-write_x_source() 
+function reload_ob() {
+    if [[ -z ${OB_PATH} ]]; then
+        printf "Error: OB_PATH not found, not reloading openbox\n"
+    else
+        sed -i -e "s/<theme>\n <name>*<\/name>/<theme>\n <name>"${OB_THEME}"<\/name>/g" "$OB_PATH/rc.xml"
+        openbox --reconfigure
+    fi
+}
+
+# Function that reloads neovim by identify all current sockets and sending
+# remote commands to each instance to reload the $MYVIMRC file
+# NOTE: Requires neovim-remote to function
+# Notes:
+#   Requires neovim-remote to function
+function reload_nvim()
 {
-   x_output=""
-   x_output+="*.foreground:   ${fg}${NEWLINE}"
-   x_output+="*.background:   ${bg}${NEWLINE}"
-   x_output+="*.cursorColor:  ${fg}${NEWLINE}"
+    if [[ ! $(command -v nvr) ]]; then
+        printf "Error:: neovim-remote not found\n"
+        printf "Please install nvr to reload neovim\n"
+    else
+        inst=($(nvr --serverlist | grep nvim | sort | uniq))
+
+        for nvim_inst in "${inst[@]}"; do 
+            nvr --servername "${nvim_inst}" --remote-send '<Esc>:so ${HOME}/.config/nvim/init.vim<CR>' &
+        done
+    fi
+}
+
+# Sends escape codes to all terminals that reflect the colors from the new colorscheme
+# Arguments: 
+#   sequence: escape codes for terminals
+# Notes:
+function reload_terminals() 
+{
+    local seq="${1}"
+
+    for term in /dev/pts/[0-9]*; do
+        printf "%b" "${seq}" > "${term}"
+    done
+}
+
+# Writes a a file specified by ${CACHE_DIR}/x_colors to be sourced by x_resources
+# Contains information about all system colors (foreground, background, cursorcolor, colors 0 - 15)
+# As well as rofi colors and 2bwm colors
+# Globals:
+#   CACHE_DIR
+# Notes:
+#   This file is only useful if it is source in ${HOME}/.Xresources
+#   This can be done with the line: 
+#       #include ".cache/squash/x_colors"
+function write_x() 
+{
+   local x_output=""
+   local x_output+="*.foreground:   ${FG}${NEWLINE}"
+   local x_output+="*.background:   ${BG}${NEWLINE}"
+   local x_output+="*.cursorColor:  ${FG}${NEWLINE}"
 
    for i in {0..15}; do
-      x_output+="*.color${i}: ${COLOR_ARRAY[${i}]}${NEWLINE}"
+      local x_output+="*.color${i}: ${color_array[${i}]}${NEWLINE}"
    done
-}
 
-write_rofi() 
-{
-   rofi_output=""
-   rofi_output+="rofi.color-enaled: true${NEWLINE}"
-   rofi_output+="rofi.color-window: ${bg}, ${bg}, ${blk}${NEWLINE}"
-   rofi_output+="rofi.color-normal: ${bg}, ${fg}, ${bg}, ${blk}, ${acc}${NEWLINE}"
-}
+   local rofi_output=""
+   local rofi_output+="rofi.color-enaled: true${NEWLINE}"
+   #local rofi_output+="rofi.color-window: ${BG}, ${BG}, ${BLK}${NEWLINE}"
+   #local rofi_output+="rofi.color-normal: ${BG}, ${FG}, ${BG}, ${BLK}, ${ACC}${NEWLINE}"
+   #                                        bg      fg     bgalt  hlbg     hlfg
+   local rofi_output+="rofi.color-window: ${BLK}, ${BLK}, ${BLK}${NEWLINE}"
+   local rofi_output+="rofi.color-normal: ${BLK}, ${FG}, ${BLK}, ${BBLK}, ${ACC}${NEWLINE}"
 
-write_2bwm() 
-{
-   twobwm_output=""
-   twobwm_output+="twobwm.focus_color: ${wht}${NEWLINE}"
-   twobwm_output+="twobwm.unfocus_color: ${blu}${NEWLINE}"
-   twobwm_output+="twobwm.fixed_color: ${wht}${NEWLINE}"
-   twobwm_output+="twobwm.unkill_color: ${wht}${NEWLINE}"
-   twobwm_output+="twobwm.outer_border_color: ${bg}${NEWLINE}"
-   twobwm_output+="twobwm.fixed_unkill_color: ${cyn}${NEWLINE}"
-}
+   local twobwm_output=""
+   local twobwm_output+="twobwm.focus_color: ${TWOBWM_FOCUS}${NEWLINE}"
+   local twobwm_output+="twobwm.unfocus_color: ${TWOBWM_FOCUS}${NEWLINE}"
+   local twobwm_output+="twobwm.fixed_color: ${TWOBWM_FIXED}${NEWLINE}"
+   local twobwm_output+="twobwm.unkill_color: ${TWOBWM_UNKILL}${NEWLINE}"
+   local twobwm_output+="twobwm.outer_border_color: ${TWOBWM_OUTR}${NEWLINE}"
+   local twobwm_output+="twobwm.fixed_unkill_color: ${TWOBWM_UNKILL}${NEWLINE}"
 
-# Writes CSS colors for use with programs such as firefox to 
-# $CACHE_DIR/colors.css
-write_css() 
-{
-   css_output=""
-   css_output+=":root {${NEWLINE}"
-   css_output+="\t--wallpaper: url("${wallpaper}");${NEWLINE}"
-   css_output+="\t--background: ${bg};${NEWLINE}"
-   css_output+="\t--foreground: ${fg};${NEWLINE}"
-   for i in {0..15}; do
-      css_output+="\t--color${i}: ${COLOR_ARRAY[${i}]};${NEWLINE}"
-   done
-   css_output+="}"
-   printf "${css_output}" > "${CACHE_DIR}/colors.css"
-}
+   if [[ $SQUASH_FONT ]]; then
+       local x_output+="URxvt*font:${SQUASH_FONT}${NEWLINE}"
+       local x_output+="URxvt*boldFont:${SQUASH_FONT}${NEWLINE}"
+   fi
 
-# Writes SH Colors for use with programs such as lemonbar
-# to $CACHE_DIR/colors
-write_sh() 
-{
-   rm -f $CACHE_DIR/colors
-   cp $THEME_DIR/$COLOR_SCHEME $CACHE_DIR/colors
-}
-
-# Writes X Output, Rofi output, and 2bwm output to x_colors
-# in $CACHE_DIR
-write_all_x() 
-{
-   output=${x_output}${rofi_output}${twobwm_output}
+   local output="${x_output}${rofi_output}${twobwm_output}"
    printf "${output}" > "${CACHE_DIR}/x_colors"
 }
 
-write_x_define() 
+# Writes a css file that contains all the color information of the current theme
+# to the ${CACHE_DIR}. Can be sourced by any number of applicatons. 
+# Globals:
+#   CACHE_DIR
+function write_css() 
 {
-   xd_output=""
-   xd_output+="#define bg   ${bg}${NEWLINE}"
-   xd_output+="#define blk   ${blk}${NEWLINE}"
-   xd_output+="#define bblk   ${bblk}${NEWLINE}"
-   xd_output+="#define fg   ${fg}${NEWLINE}"
-   xd_output+="#define red   ${red}${NEWLINE}"
-   xd_output+="#define bred   ${bred}${NEWLINE}"
-   xd_output+="#define grn   ${grn}${NEWLINE}"
-   xd_output+="#define bgrn   ${bgrn}${NEWLINE}"
-   xd_output+="#define ylw   ${ylw}${NEWLINE}"
-   xd_output+="#define bylw   ${bylw}${NEWLINE}"
-   xd_output+="#define blu   ${blu}${NEWLINE}"
-   xd_output+="#define bblu   ${bblu}${NEWLINE}"
-   xd_output+="#define mag   ${mag}${NEWLINE}"
-   xd_output+="#define bmag   ${bmag}${NEWLINE}"
-   xd_output+="#define cyn   ${cyn}${NEWLINE}"
-   xd_output+="#define bcyn   ${bcyn}${NEWLINE}"
-   xd_output+="#define wht   ${wht}${NEWLINE}"
-   xd_output+="#define bwht   ${bwht}${NEWLINE}"
+   local css_output=""
+   local css_output+=":root {${NEWLINE}"
+   local css_output+="\t--wallpaper: url("${wallpaper}");${NEWLINE}"
+   local css_output+="\t--background: ${BG};${NEWLINE}"
+   local css_output+="\t--foreground: ${FG};${NEWLINE}"
+   for i in {0..15}; do 
+       local css_output+="\t--color${i}: ${color_array[${i}]};${NEWLINE}"
+   done
+   local css_output+="}"
 
-   printf "${xd_output}" > "$CACHE_DIR/xd_colors"
+   printf "${css_output}" > "${CACHE_DIR}/colors.css"
 }
 
-if [ -f $THEME_DIR/$COLOR_SCHEME ]; then
-    # Remove old colors
-    cleanup
+# Copies the current bash script to the ${CACHE_DIR} so that it can be sourced by any applications
+# that want access to the variables in the bash script
+# Globals:
+#   CACHE_DIR
+function write_sh() 
+{
+    rm -f ${CACHE_DIR}/colors
+    cp ${THEME_DIR}/${COLOR_SCHEME} ${CACHE_DIR}/colors
+}
 
-    # Source color directory
-    get_colors
+# Write all files
+write_x
+write_sh
+write_css
 
-    # Create sequence to reload opened terminals
-    create_main_sequence
-    create_secondary_sequence
+# Source .Xresources
+xrdb "${HOME}/.Xresources"
 
-    # Reload all x terminals
-    reload_x
-
-    # Write all colors files to .cahe
-    write_x_source
-    write_rofi
-    write_2bwm
-    write_all_x
-    write_css
-    write_sh
-    write_x_define
-
-    # Merge x colors
-    merge_x
-
-    # Recompile and reload 2bwm
-    # Reload bar
-    if [[ $WM == "2bwm" ]]; then
-        reload_2bwm
-    fi
-    reload_lemonbar
-
-    # Set wallpaper
-    set_wallpaper
-else
-    printf "ERROR : THEME FILE NOT FOUND"
-fi
+# Update applications
+update_wall
+update_terminals
+update_nvim
+update_bar
+update_wm
+update_dunst
